spring:
  datasource:
#    driver-class-name: org.postgresql.Driver  # spring boot will find the driver class name
    url: jdbc:postgresql://localhost:5432/testdb
    database: testdb
    username: postgres
    password: thrymr@123